version: '2'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8050:80"
    environment:
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
       - ./pgadmin/servers.json:/pgadmin4/servers.json

  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:16
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_odoo
      - POSTGRESQL_DATABASE=bitnami_odoo

  odoo:
    container_name: odoo
    image: docker.io/bitnami/odoo:16.0.20240215-debian-12-r2
    ports:
      - '80:8069'
    volumes:
      - 'odoo_data:/bitnami/odoo'
      - ../odoo-addons:/bitnami/odoo/data/addons/16.0
      - ${PWD}/odoo.conf:/bitnami/odoo/conf/odoo.conf
    depends_on:
      - postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - ODOO_DATABASE_HOST=postgresql
      - ODOO_DATABASE_PORT_NUMBER=5432
      - ODOO_DATABASE_USER=bn_odoo
      - ODOO_DATABASE_NAME=bitnami_odoo

volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local